-- Optional persistence schema for Supabase.
-- Run this in Supabase SQL Editor before enabling SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY.

create table if not exists public.ai_generations (
  id bigint generated by default as identity primary key,
  request_id text not null,
  type text not null check (type in ('chat', 'image')),
  prompt text not null,
  result jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists ai_generations_created_at_idx
  on public.ai_generations (created_at desc);

alter table public.ai_generations enable row level security;

-- The service role key is used only by the serverless backend and bypasses RLS.
-- Do not expose SUPABASE_SERVICE_ROLE_KEY in frontend code.
